import type {
  EquityPoint,
  MonthlyPerformance,
  Trade,
} from "@/app/_lib/trading-types";

export const initialTradingReport = null;

export const fallbackTradeHistory: Trade[] = [
  {
    id: "TNPA-C1",
    source: "mt5",
    accountType: "prop-firm",
    accountName: "FTMO",
    strategyType: "Intraweek",
    firmName: "FTMO",
    accountSize: 100000,
    challengeType: "2-Step Challenge",
    phase: "Phase 1",
    profitTargetPercent: 10,
    dailyLossLimitPercent: 5,
    maxLossLimitPercent: 10,
    minimumTradingDays: 4,
    propStatus: "Active",
    symbol: "XAUUSD",
    setup: "London liquidity sweep",
    setupTag: "Breakout Trendline",
    playbook: "London Breakout Trendline",
    status: "Closed",
    side: "Long",
    date: "May 29, 2026",
    session: "London",
    entry: 2326.4,
    exit: 2340.8,
    rr: 2.6,
    pnl: 4280,
    result: "Win",
  },
  {
    id: "TNPA-C2",
    source: "mt5",
    accountType: "prop-firm",
    accountName: "FTMO",
    strategyType: "Intraweek",
    firmName: "FTMO",
    accountSize: 100000,
    challengeType: "2-Step Challenge",
    phase: "Phase 1",
    profitTargetPercent: 10,
    dailyLossLimitPercent: 5,
    maxLossLimitPercent: 10,
    minimumTradingDays: 4,
    propStatus: "Active",
    symbol: "EURUSD",
    setup: "NY continuation",
    setupTag: "Trading Range",
    playbook: "NY Continuation",
    status: "Closed",
    side: "Short",
    date: "May 28, 2026",
    session: "New York",
    entry: 1.0872,
    exit: 1.0821,
    rr: 1.9,
    pnl: 2140,
    result: "Win",
  },
  {
    id: "TNPA-C3",
    source: "mt5",
    accountType: "prop-firm",
    accountName: "FTMO",
    strategyType: "Intraweek",
    firmName: "FTMO",
    accountSize: 100000,
    challengeType: "2-Step Challenge",
    phase: "Phase 1",
    profitTargetPercent: 10,
    dailyLossLimitPercent: 5,
    maxLossLimitPercent: 10,
    minimumTradingDays: 4,
    propStatus: "Active",
    symbol: "NAS100",
    setup: "Opening range failure",
    setupTag: "Trading Range",
    playbook: "Trading Range Reversal",
    status: "Closed",
    side: "Short",
    date: "May 27, 2026",
    session: "New York",
    entry: 18892,
    exit: 18966,
    rr: -1,
    pnl: -1250,
    result: "Loss",
  },
  {
    id: "TNPA-C4",
    source: "mt5",
    accountType: "prop-firm",
    accountName: "FTMO",
    strategyType: "Intraweek",
    firmName: "FTMO",
    accountSize: 100000,
    challengeType: "2-Step Challenge",
    phase: "Phase 1",
    profitTargetPercent: 10,
    dailyLossLimitPercent: 5,
    maxLossLimitPercent: 10,
    minimumTradingDays: 4,
    propStatus: "Active",
    symbol: "GBPJPY",
    setup: "HTF order block",
    setupTag: "Supply Demand",
    playbook: "Supply Demand Reversal",
    status: "Closed",
    side: "Long",
    date: "May 24, 2026",
    session: "London",
    entry: 199.42,
    exit: 200.31,
    rr: 3.1,
    pnl: 3860,
    result: "Win",
  },
  {
    id: "TNPA-C5",
    source: "mt5",
    accountType: "prop-firm",
    accountName: "FTMO",
    strategyType: "Intraweek",
    firmName: "FTMO",
    accountSize: 100000,
    challengeType: "2-Step Challenge",
    phase: "Phase 1",
    profitTargetPercent: 10,
    dailyLossLimitPercent: 5,
    maxLossLimitPercent: 10,
    minimumTradingDays: 4,
    propStatus: "Active",
    symbol: "US30",
    setup: "Rejection at value high",
    setupTag: "Rectangle Range",
    playbook: "Rectangle Range",
    status: "Open",
    side: "Short",
    date: "May 22, 2026",
    session: "New York",
    entry: 39220,
    rr: 0,
    result: "Open",
    floatingPnl: 640,
  } as unknown as Trade,
];

export const fallbackEquityCurve: EquityPoint[] = [
  { label: "Jan", equity: 100000 },
  { label: "Feb", equity: 103450 },
  { label: "Mar", equity: 101980 },
  { label: "Apr", equity: 109720 },
  { label: "May", equity: 116480 },
];

export const fallbackMonthlyPerformance: MonthlyPerformance[] = [
  { month: "Jan", pnl: 3450 },
  { month: "Feb", pnl: 6120 },
  { month: "Mar", pnl: -1470 },
  { month: "Apr", pnl: 7740 },
  { month: "May", pnl: 6760 },
];
