import { loadMt5Report } from "@/app/_lib/mt5-html-parser";
import { getDefaultPlaybook } from "@/app/_lib/playbook-storage";
import { getDefaultSetupTag } from "@/app/_lib/setup-tag-storage";
import {
  buildEquityCurve,
  buildKpis,
  buildMonthlyPerformance,
} from "@/app/_lib/trading-metrics";
import type {
  EquityPoint,
  MonthlyPerformance,
  Trade,
} from "@/app/_lib/trading-types";
export type { EquityPoint, Kpi, MonthlyPerformance, Trade } from "@/app/_lib/trading-types";

type TradeWithOptionalPlaybook = Omit<Trade, "playbook"> &
  Partial<Pick<Trade, "playbook">>;

const mockTradeHistory: TradeWithOptionalPlaybook[] = [
  {
    id: "TNPA-2491",
    symbol: "XAUUSD",
    setup: "London liquidity sweep",
    setupTag: "Breakout Trendline",
    status: "Closed",
    side: "Long",
    date: "May 29, 2026",
    session: "London",
    entry: 2326.4,
    exit: 2340.8,
    rr: 2.6,
    pnl: 4280,
    result: "Win",
  },
  {
    id: "TNPA-2488",
    symbol: "EURUSD",
    setup: "NY continuation",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Short",
    date: "May 28, 2026",
    session: "New York",
    entry: 1.0872,
    exit: 1.0821,
    rr: 1.9,
    pnl: 2140,
    result: "Win",
  },
  {
    id: "TNPA-2482",
    symbol: "NAS100",
    setup: "Opening range failure",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Short",
    date: "May 27, 2026",
    session: "New York",
    entry: 18892,
    exit: 18966,
    rr: -1,
    pnl: -1250,
    result: "Loss",
  },
  {
    id: "TNPA-2475",
    symbol: "GBPJPY",
    setup: "HTF order block",
    setupTag: "Supply Demand",
    status: "Closed",
    side: "Long",
    date: "May 24, 2026",
    session: "London",
    entry: 199.42,
    exit: 200.31,
    rr: 3.1,
    pnl: 3860,
    result: "Win",
  },
  {
    id: "TNPA-2468",
    symbol: "US30",
    setup: "Rejection at value high",
    setupTag: "Rectangle Range",
    status: "Closed",
    side: "Short",
    date: "May 22, 2026",
    session: "New York",
    entry: 39220,
    exit: 39314,
    rr: -0.8,
    pnl: -980,
    result: "Loss",
  },
  {
    id: "TNPA-2459",
    symbol: "XAUUSD",
    setup: "London liquidity sweep",
    setupTag: "Breakout Trendline",
    status: "Closed",
    side: "Short",
    date: "May 20, 2026",
    session: "London",
    entry: 2414.2,
    exit: 2397.5,
    rr: 2.3,
    pnl: 3350,
    result: "Win",
  },
  {
    id: "TNPA-2447",
    symbol: "USDJPY",
    setup: "Asian range breakout",
    setupTag: "Breakout Trendline",
    status: "Closed",
    side: "Long",
    date: "May 17, 2026",
    session: "Asia",
    entry: 156.22,
    exit: 156.84,
    rr: 1.5,
    pnl: 1420,
    result: "Win",
  },
  {
    id: "TNPA-2439",
    symbol: "EURUSD",
    setup: "NY continuation",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Long",
    date: "May 15, 2026",
    session: "New York",
    entry: 1.0744,
    exit: 1.0708,
    rr: -1,
    pnl: -1120,
    result: "Loss",
  },
  {
    id: "TNPA-2431",
    symbol: "NAS100",
    setup: "Opening range failure",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Long",
    date: "May 13, 2026",
    session: "New York",
    entry: 18440,
    exit: 18616,
    rr: 2.1,
    pnl: 2980,
    result: "Win",
  },
  {
    id: "TNPA-2418",
    symbol: "GBPJPY",
    setup: "HTF order block",
    setupTag: "Supply Demand",
    status: "Closed",
    side: "Short",
    date: "May 9, 2026",
    session: "London",
    entry: 197.9,
    exit: 198.28,
    rr: -0.7,
    pnl: -860,
    result: "Loss",
  },
  {
    id: "TNPA-2404",
    symbol: "US30",
    setup: "Rejection at value high",
    setupTag: "Rectangle Range",
    status: "Closed",
    side: "Long",
    date: "May 6, 2026",
    session: "New York",
    entry: 38680,
    exit: 38892,
    rr: 1.8,
    pnl: 2440,
    result: "Win",
  },
  {
    id: "TNPA-2398",
    symbol: "XAUUSD",
    setup: "FVG mitigation",
    setupTag: "Supply Demand",
    status: "Closed",
    side: "Long",
    date: "May 3, 2026",
    session: "London",
    entry: 2298.6,
    exit: 2311.2,
    rr: 2.4,
    pnl: 3720,
    result: "Win",
  },
  {
    id: "TNPA-2385",
    symbol: "EURUSD",
    setup: "FVG mitigation",
    setupTag: "Supply Demand",
    status: "Closed",
    side: "Short",
    date: "Apr 30, 2026",
    session: "New York",
    entry: 1.0661,
    exit: 1.0689,
    rr: -1,
    pnl: -1040,
    result: "Loss",
  },
  {
    id: "TNPA-2372",
    symbol: "USDJPY",
    setup: "Asian range breakout",
    setupTag: "Breakout Trendline",
    status: "Closed",
    side: "Short",
    date: "Apr 26, 2026",
    session: "Asia",
    entry: 154.88,
    exit: 154.17,
    rr: 1.7,
    pnl: 1880,
    result: "Win",
  },
  {
    id: "TNPA-2360",
    symbol: "NAS100",
    setup: "NY continuation",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Long",
    date: "Apr 23, 2026",
    session: "New York",
    entry: 18110,
    exit: 18334,
    rr: 2.8,
    pnl: 4560,
    result: "Win",
  },
  {
    id: "TNPA-2348",
    symbol: "GBPJPY",
    setup: "London liquidity sweep",
    setupTag: "Breakout Trendline",
    status: "Closed",
    side: "Short",
    date: "Apr 19, 2026",
    session: "London",
    entry: 195.66,
    exit: 194.81,
    rr: 2,
    pnl: 2320,
    result: "Win",
  },
  {
    id: "TNPA-2335",
    symbol: "US30",
    setup: "Opening range failure",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Short",
    date: "Apr 16, 2026",
    session: "New York",
    entry: 38110,
    exit: 38200,
    rr: -0.9,
    pnl: -1180,
    result: "Loss",
  },
  {
    id: "TNPA-2321",
    symbol: "XAUUSD",
    setup: "HTF order block",
    setupTag: "Supply Demand",
    status: "Closed",
    side: "Long",
    date: "Apr 12, 2026",
    session: "London",
    entry: 2244.8,
    exit: 2268.9,
    rr: 3.4,
    pnl: 5480,
    result: "Win",
  },
  {
    id: "TNPA-2307",
    symbol: "EURUSD",
    setup: "Rejection at value high",
    setupTag: "Rectangle Range",
    status: "Closed",
    side: "Short",
    date: "Apr 8, 2026",
    session: "New York",
    entry: 1.0557,
    exit: 1.0518,
    rr: 1.6,
    pnl: 1780,
    result: "Win",
  },
  {
    id: "TNPA-2294",
    symbol: "USDJPY",
    setup: "FVG mitigation",
    setupTag: "Supply Demand",
    status: "Closed",
    side: "Long",
    date: "Apr 4, 2026",
    session: "Asia",
    entry: 152.6,
    exit: 152.14,
    rr: -0.6,
    pnl: -760,
    result: "Loss",
  },
  {
    id: "TNPA-2281",
    symbol: "NAS100",
    setup: "Opening range failure",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Short",
    date: "Mar 29, 2026",
    session: "New York",
    entry: 17844,
    exit: 17692,
    rr: 2.2,
    pnl: 3160,
    result: "Win",
  },
  {
    id: "TNPA-2269",
    symbol: "GBPJPY",
    setup: "NY continuation",
    setupTag: "Trading Range",
    status: "Closed",
    side: "Long",
    date: "Mar 24, 2026",
    session: "New York",
    entry: 193.21,
    exit: 192.74,
    rr: -1,
    pnl: -1320,
    result: "Loss",
  },
  {
    id: "TNPA-2256",
    symbol: "US30",
    setup: "Rejection at value high",
    setupTag: "Rectangle Range",
    status: "Closed",
    side: "Short",
    date: "Mar 20, 2026",
    session: "New York",
    entry: 37420,
    exit: 37210,
    rr: 2.1,
    pnl: 2860,
    result: "Win",
  },
  {
    id: "TNPA-2242",
    symbol: "XAUUSD",
    setup: "London liquidity sweep",
    setupTag: "Breakout Trendline",
    status: "Closed",
    side: "Long",
    date: "Mar 15, 2026",
    session: "London",
    entry: 2186.1,
    exit: 2175.7,
    rr: -1,
    pnl: -1460,
    result: "Loss",
  },
];

export const importedMt5Report = loadMt5Report();
const sourceTradeHistory: TradeWithOptionalPlaybook[] = (
  importedMt5Report?.trades ?? mockTradeHistory
);

export const tradeHistory: Trade[] = sourceTradeHistory.map((trade) => ({
  ...trade,
  source: trade.source ?? "mt5",
  accountType: trade.accountType ?? importedMt5Report?.accountType ?? "prop-firm",
  accountId: trade.accountId ?? trade.account_id ?? importedMt5Report?.accountId ?? importedMt5Report?.account_id,
  account_id: trade.account_id ?? trade.accountId ?? importedMt5Report?.account_id ?? importedMt5Report?.accountId,
  accountName: trade.accountName ?? importedMt5Report?.accountName ?? importedMt5Report?.name ?? "FTMO",
  strategyType: trade.strategyType ?? importedMt5Report?.strategyType ?? "Intraweek",
  firmName: trade.firmName ?? importedMt5Report?.firmName ?? "FTMO",
  accountSize: trade.accountSize ?? importedMt5Report?.accountSize ?? 100000,
  challengeType: trade.challengeType ?? importedMt5Report?.challengeType ?? "FTMO Challenge V2",
  phase: trade.phase ?? importedMt5Report?.phase ?? "Phase 1",
  profitTargetPercent: trade.profitTargetPercent ?? importedMt5Report?.profitTargetPercent ?? 10,
  dailyLossLimitPercent: trade.dailyLossLimitPercent ?? importedMt5Report?.dailyLossLimitPercent ?? 5,
  maxLossLimitPercent: trade.maxLossLimitPercent ?? importedMt5Report?.maxLossLimitPercent ?? 10,
  minimumTradingDays: trade.minimumTradingDays ?? importedMt5Report?.minimumTradingDays ?? 4,
  startDate: trade.startDate ?? importedMt5Report?.startDate,
  propStatus: trade.propStatus ?? importedMt5Report?.propStatus ?? "Active",
  setupTag: trade.setupTag ?? getDefaultSetupTag(trade.setup),
  playbook:
    trade.playbook ??
    getDefaultPlaybook(trade.setup, trade.setupTag ?? getDefaultSetupTag(trade.setup)),
}));
export const recentTrades: Trade[] = tradeHistory.slice(0, 5);

export const kpis = buildKpis(tradeHistory, importedMt5Report);

const mockEquityCurve: EquityPoint[] = [
  { label: "Jan", equity: 100000 },
  { label: "Feb", equity: 103450 },
  { label: "Mar", equity: 101980 },
  { label: "Apr", equity: 109720 },
  { label: "May", equity: 116480 },
  { label: "Jun", equity: 114900 },
  { label: "Jul", equity: 121600 },
  { label: "Aug", equity: 128240 },
  { label: "Sep", equity: 126700 },
  { label: "Oct", equity: 136100 },
  { label: "Nov", equity: 141380 },
  { label: "Dec", equity: 148920 },
];

const mockMonthlyPerformance: MonthlyPerformance[] = [
  { month: "Jan", pnl: 3450 },
  { month: "Feb", pnl: 6120 },
  { month: "Mar", pnl: -1470 },
  { month: "Apr", pnl: 7740 },
  { month: "May", pnl: 6760 },
  { month: "Jun", pnl: -1580 },
  { month: "Jul", pnl: 6700 },
  { month: "Aug", pnl: 6640 },
  { month: "Sep", pnl: -1540 },
  { month: "Oct", pnl: 9400 },
  { month: "Nov", pnl: 5280 },
  { month: "Dec", pnl: 7540 },
];

export const mockEquityCurveFallback = mockEquityCurve;
export const mockMonthlyPerformanceFallback = mockMonthlyPerformance;
export const equityCurve: EquityPoint[] = buildEquityCurve(
  tradeHistory,
  importedMt5Report,
  mockEquityCurve,
);
export const monthlyPerformance: MonthlyPerformance[] =
  buildMonthlyPerformance(
    tradeHistory,
    importedMt5Report,
    mockMonthlyPerformance,
  );
